FROM node:14.15.4 AS build
RUN apt update \
    && apt-get install -y default-jre \
    && curl https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -o /chrome.deb \
    && apt-get update && dpkg -i /chrome.deb \
    || apt-get install --no-install-recommends -yf \
    && rm /chrome.deb \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
RUN npm i -g @angular/cli
WORKDIR /hub

COPY ./client/package.json .
RUN npm i

COPY ./client/.browserslistrc ./client/tslint.json ./client/tsconfig.app.json ./client/tsconfig.json ./client/angular.json ./
COPY ./client/src/ ./src/
RUN ng build --prod

COPY ./client/tsconfig.spec.json ./client/karma.conf.js ./
COPY ./client/e2e/ ./e2e/
RUN npm run test
# RUN npm run e2e

FROM nginx AS run
COPY --from=build /hub/dist/* /usr/share/nginx/html/
COPY ./client/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80