FROM node:14.15.4
RUN apt update \
    && apt-get install -y default-jre \
    && curl https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -o /chrome.deb \
    && apt-get update && dpkg -i /chrome.deb \
    || apt-get install --no-install-recommends -yf \
    && rm /chrome.deb \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

#CMD curl http://localhost:4200

RUN npm i @angular/cli@12

WORKDIR /test

COPY ./test/package.json .
RUN npm i
RUN npm install typescript

COPY ./test/env.ts ./test/tsconfig.json ./test/protractor.ts ./
COPY ./test/src/ ./src/
 
RUN npm run test